[package]
name = "challMac"
version = "0.1.0"
edition = "2021"

[dependencies]
hmac = "0.12"
sha2 = "0.10"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "challmac"
path = "src/main.rs" 
